class Localization:
    en = "en"
    fr = "fr"
    de = "de"
    it = "it"
    es = "es"
    es_mx = "es-mx"
    pt_br = "pt-br"
    ru = "ru"
    pl = "pl"
    ja = "ja"
    ko = "ko"
    zh_cht = "zh-cht"
    zh_chs = "zh-chs"
